### ISSUE TITLE
Add a Retrieve File method to ZipRangeReader

### ISSUE THREAD

**Issue by DiegoPino** [digitaldogsbody/mingulay#1]
# What?

With the info retrieve from the central directory and knowing the offset of a File, using the same range/seek logic we can fetch a single file by selecting only those ranges and decompressing on the fly.

ZipRangeReader could provide that method

I suggest we go for?

`::getStream($URI)`

**Comment by digitaldogsbody** [comment]
This is useful functionality, we should add it for sure. Need to have a think about the semantics of this - how to tell ZRR which file you want.

Options:
1) Call function by filename (as per your suggestion if I understand it right)
    - Currently the files index is just an unkeyed array, so we would have to do an array find to locate which record we need
    - Alternatively we could re-key the files array by filename and then we can do a straight get
2) Call function by index (since this should be immutable)
    - Major con is this requires a slightly messier pattern for the end-user, especially if they are listing the files and allowing the user to select, or maybe having a "extract all files matching `*.tiff` or similar, since they now have to track the index as well.
3) Add a class for ZipFileObject, convert the `files` function to return those, and then one can be passed by reference
    - i.e `getStream(ZipFileObject $object)`
    - Maybe still messy for the end user?
    - Could expose a `getStream()` on the ZipFileObject itself as well
      -  This would probably still have to call the function on the parent ZipRangeReader class? ZipFileObject won't necessarily have knowledge of the seeker, although we could pass this in the constructor.

Thoughts?

**Comment by DiegoPino** [comment]
@digitaldogsbody thanks. Was thinking following the structure of 
https://www.php.net/manual/en/class.ziparchive.php because basically your library does a few things but in a more clever (central directory) way. Why defer to that method? Because that might be more familiar for PHP users.

This is how I imaged the method

1.-  Only the `path` is passed and it returns a file(stream or pointer). In PHP Objects are always by reference but passing a ZipFileObject might be redundant because a PHP user will want to use directly the file in PHP native way.
2.- On invocation `ZipRangeReader::getStream` will check if the ZipRangeReader Object already has the `Directory` stored in a private property, if not will call itself to generate the Directory (bad idea?) and invert the index so filenames are index, index number are values (search hash) and check if that `path` is there. If not return NULL/throw exception (would be great if the response would match the class.ziparchive::getStream response). If there use the seeker to fetch/decompress the file using also ranges (reading chunks?) and returning. That way getStream can be consumed as "while not EOF do", in almost code (might have tons of errors!) something like?
```
$ZipRangeReaderObject = new $ZipRange($zip_file_path);
 if ($ZipRangeReaderObject) {
        $fp = $ZipRangeReaderObject->getStream($uri);
        if (!$fp) {
          return FALSE;
        }
        while (!feof($fp)) {
          $contents .= fread($fp, 2);
        }
        fclose($fp);

```

**Comment by digitaldogsbody** [comment]
That looks good to me.

So for (1) we go with re-keying by filename in the `$files` array (I think this is a good idea anyway) and then a straight lookup when `getStream(string $path)` is called.
For (2), the directory is populated as part of the constructor, so there shouldn't be any need to check/call, as by the time the user has the instantiated ZipRangeReader returned from the `new ZipRangeReader($seeker)` call, it will either have errored out (if the zipfile is bad / seeker is broken etc) or it will have the file list already.

The signature for `ZipArchive::getStream()` is `resource|false`. We can match this fine, but without the full typehint (until PHP8 and union typing, anyway). My only feeling is that in the rest of the library we are throwing exceptions or returning NULL, so returning false here would be a little inconsistent? (I assume the fact that a lot of PHP core functions return false rather than an error is a holdover from before PHP had try/catch?)

**Comment by DiegoPino** [comment]
I agree with you. NULL is OK
and exceptions. I love consistency
